# Generated by Django 3.0.3 on 2020-03-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imdbId',
            field=models.CharField(default='NO-ID', max_length=100),
            preserve_default=False,
        ),
    ]
