# Generated by Django 3.0.3 on 2020-03-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_imdbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='id',
        ),
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
        migrations.AlterField(
            model_name='film',
            name='imdbId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
