# Generated by Django 3.0.3 on 2020-03-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20200302_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('imdbId', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
