# Generated by Django 3.0.3 on 2020-03-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='box_office',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='cast',
            field=models.ManyToManyField(related_name='cast', to='films.People'),
        ),
        migrations.AddField(
            model_name='film',
            name='counties',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='cover_url',
            field=models.URLField(default='http://www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='director', to='films.People'),
        ),
        migrations.AddField(
            model_name='film',
            name='kind',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='production_companies',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='synopsis',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='top_250_films',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='writer',
            field=models.ManyToManyField(related_name='writer', to='films.People'),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
