# Generated by Django 3.0.3 on 2020-03-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20200303_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='film',
            name='production_companies',
        ),
        migrations.AlterField(
            model_name='film',
            name='box_office',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='film',
            name='cast',
        ),
        migrations.AddField(
            model_name='film',
            name='cast',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='film',
            name='writer',
        ),
        migrations.AddField(
            model_name='film',
            name='writer',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
