# Generated by Django 3.0.3 on 2020-03-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20200303_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='counties',
            new_name='countries',
        ),
    ]
