# Generated by Django 3.0.3 on 2020-03-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_auto_20200303_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='box_office',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(),
        ),
    ]
