# Generated by Django 3.0.3 on 2020-03-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_auto_20200303_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='fullsize_poster',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
