# Generated by Django 3.0.3 on 2020-03-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_film_fullsize_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='search_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
