# Generated by Django 3.0.3 on 2020-03-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_film_search_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='search_time',
            field=models.IntegerField(default=0),
        ),
    ]
