# Generated by Django 3.0.3 on 2020-03-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_comment'),
        ('films', '0011_auto_20200304_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='comments',
            field=models.ManyToManyField(to='accounts.Comment'),
        ),
    ]
