# Generated by Django 3.0.3 on 2020-03-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        ('accounts', '0003_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_films',
            field=models.ManyToManyField(to='films.Film'),
        ),
    ]
