# Generated by Django 3.0.3 on 2020-03-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_watched_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watched_films',
        ),
    ]
