# Generated by Django 3.0.3 on 2020-03-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_auto_20200303_0907'),
        ('accounts', '0006_user_watched_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watched_films',
            field=models.ManyToManyField(blank=True, to='films.Film'),
        ),
    ]
