# Generated by Django 3.0.3 on 2020-03-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_film_fullsize_poster'),
        ('accounts', '0007_auto_20200303_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_list',
            field=models.ManyToManyField(blank=True, related_name='fav', to='films.Film'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watched_films',
            field=models.ManyToManyField(blank=True, related_name='watched', to='films.Film'),
        ),
    ]
