# Generated by Django 3.0.3 on 2020-03-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='No-Image', upload_to='avatars'),
        ),
    ]
