# Generated by Django 3.0.3 on 2020-03-06 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_requested_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='friends_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
