# Generated by Django 3.0.3 on 2020-03-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_suggest'),
        ('accounts', '0017_auto_20200306_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suggests',
            field=models.ManyToManyField(blank=True, null=True, related_name='suggests', to='films.Suggest'),
        ),
    ]
